application: paste
version: 1
runtime: python
api_version: 1

handlers:

- url: /css/
  static_dir: css

- url: /js/
  static_dir: js

- url: /images/
  static_dir: images 

- url: /f/.*
  script: feed.py
  
- url: /.*
  script: main.py

